sudo: false
language: go
go: go1.7
install:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/ahmetalpbalkan/govvv
before_script:
  - env
  - ls -al $GOPATH/bin
  - which golint
script:
  - test -z "$(gofmt -s -l . | grep -v vendor/ | tee /dev/stderr)"
  - test -z "$(golint . | tee /dev/stderr)"
  - go list ./... | grep -v vendor | xargs go vet -v
  - go list ./... | grep -v vendor | xargs go test -v -cover
